services:
    db:
        image: postgres:16
        container_name: trip_planner_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: trip_planner
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7
        container_name: trip_planner_redis
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        command: ['redis-server', '--appendonly', 'yes']

    pgadmin:
        image: dpage/pgadmin4
        container_name: trip_planner_pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '8080:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - db

volumes:
    db_data:
    redis_data:
    pgadmin_data:
